// ********************************************************
// Copyright (C) 2022 Louis S. Berman (louis@squideyes.com)
//
// This file is part of SquidEyes.FxData
//
// The use of this source code is licensed under the terms
// of the MIT License (https://opensource.org/licenses/MIT)
// ********************************************************

namespace SquidEyes.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SquidEyes.UnitTests.Properties.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/04/2016 08:00:00.062,1.11982,1.11983
        ///01/04/2016 08:00:00.164,1.11984,1.11985
        ///01/04/2016 08:00:00.576,1.11986,1.11988
        ///01/04/2016 08:00:00.678,1.11987,1.11988
        ///01/04/2016 08:00:00.779,1.11987,1.11989
        ///01/04/2016 08:00:01.083,1.11987,1.11988
        ///01/04/2016 08:00:01.337,1.11987,1.11989
        ///01/04/2016 08:00:06.658,1.11987,1.11990
        ///01/04/2016 08:00:06.760,1.11990,1.11992
        ///01/04/2016 08:00:06.861,1.11991,1.11993
        ///01/04/2016 08:00:06.963,1.11991,1.11994
        ///01/04/2016 08:00:07.702,1.11990,1.11994
        ///01/04/2016 08:00:08. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20160104_NYC_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20160104_NYC_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160104_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160104_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/05/2016 08:00:00.092,1.11746,1.11749
        ///01/05/2016 08:00:00.345,1.11746,1.11748
        ///01/05/2016 08:00:00.446,1.11746,1.11749
        ///01/05/2016 08:00:00.791,1.11747,1.11749
        ///01/05/2016 08:00:00.893,1.11747,1.11750
        ///01/05/2016 08:00:01.789,1.11746,1.11748
        ///01/05/2016 08:00:01.890,1.11746,1.11749
        ///01/05/2016 08:00:02.042,1.11747,1.11749
        ///01/05/2016 08:00:02.194,1.11746,1.11749
        ///01/05/2016 08:00:02.397,1.11747,1.11750
        ///01/05/2016 08:00:02.498,1.11746,1.11750
        ///01/05/2016 08:00:03.060,1.11748,1.11750
        ///01/05/2016 08:00:06. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20160105_NYC_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20160105_NYC_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160105_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160105_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/06/2016 08:00:00.403,1.11166,1.11167
        ///01/06/2016 08:00:00.505,1.11165,1.11167
        ///01/06/2016 08:00:00.606,1.11165,1.11168
        ///01/06/2016 08:00:00.707,1.11165,1.11167
        ///01/06/2016 08:00:00.852,1.11164,1.11167
        ///01/06/2016 08:00:00.954,1.11165,1.11167
        ///01/06/2016 08:00:01.119,1.11165,1.11168
        ///01/06/2016 08:00:01.220,1.11166,1.11169
        ///01/06/2016 08:00:01.322,1.11168,1.11170
        ///01/06/2016 08:00:01.423,1.11172,1.11173
        ///01/06/2016 08:00:01.525,1.11172,1.11174
        ///01/06/2016 08:00:01.676,1.11173,1.11175
        ///01/06/2016 08:00:01. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20160106_NYC_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20160106_NYC_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160106_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160106_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/07/2016 08:00:00.327,1.11135,1.11138
        ///01/07/2016 08:00:00.985,1.11135,1.11136
        ///01/07/2016 08:00:01.087,1.11134,1.11137
        ///01/07/2016 08:00:01.189,1.11134,1.11135
        ///01/07/2016 08:00:01.290,1.11132,1.11133
        ///01/07/2016 08:00:01.393,1.11130,1.11134
        ///01/07/2016 08:00:01.494,1.11130,1.11133
        ///01/07/2016 08:00:02.047,1.11130,1.11134
        ///01/07/2016 08:00:02.148,1.11131,1.11134
        ///01/07/2016 08:00:02.300,1.11132,1.11135
        ///01/07/2016 08:00:02.753,1.11134,1.11135
        ///01/07/2016 08:00:02.805,1.11135,1.11136
        ///01/07/2016 08:00:02. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20160107_NYC_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20160107_NYC_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160107_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160107_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/08/2016 08:00:00.409,1.10984,1.10986
        ///01/08/2016 08:00:00.460,1.10982,1.10986
        ///01/08/2016 08:00:00.613,1.10983,1.10986
        ///01/08/2016 08:00:01.036,1.10982,1.10986
        ///01/08/2016 08:00:01.240,1.10983,1.10986
        ///01/08/2016 08:00:01.393,1.10982,1.10986
        ///01/08/2016 08:00:02.525,1.10983,1.10986
        ///01/08/2016 08:00:04.664,1.10982,1.10985
        ///01/08/2016 08:00:07.554,1.10982,1.10984
        ///01/08/2016 08:00:08.169,1.10982,1.10985
        ///01/08/2016 08:00:08.270,1.10981,1.10984
        ///01/08/2016 08:00:08.371,1.10982,1.10984
        ///01/08/2016 08:00:09. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20160108_NYC_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20160108_NYC_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160108_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160108_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/04/2016 08:00:06.963,1.11991,1.11994,01/04/2016 08:00:00.062,1.11983,01/04/2016 08:00:06.963,1.11993
        ///01/04/2016 08:04:13.432,1.12001,1.12004,01/04/2016 08:00:06.963,1.11993,01/04/2016 08:04:13.432,1.12003
        ///01/04/2016 08:06:45.115,1.11980,1.11981,01/04/2016 08:04:13.432,1.11993,01/04/2016 08:06:45.115,1.11983
        ///01/04/2016 08:10:12.220,1.11971,1.11972,01/04/2016 08:06:45.115,1.11983,01/04/2016 08:10:12.220,1.11973
        ///01/04/2016 08:11:41.507,1.11959,1.11961,01/04/2016 08:10:12.220,1.11973,01/04/2016 08:11:41. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RENKOFEEDTESTS_4_ASK {
            get {
                return ResourceManager.GetString("RENKOFEEDTESTS_4_ASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/04/2016 08:00:48.436,1.11993,1.11995,01/04/2016 08:00:00.062,1.11982,01/04/2016 08:00:48.436,1.11992
        ///01/04/2016 08:08:28.678,1.11971,1.11973,01/04/2016 08:00:48.436,1.11982,01/04/2016 08:08:28.678,1.11972
        ///01/04/2016 08:11:41.140,1.11961,1.11964,01/04/2016 08:08:28.678,1.11972,01/04/2016 08:11:41.140,1.11962
        ///01/04/2016 08:14:21.330,1.11951,1.11953,01/04/2016 08:11:41.140,1.11962,01/04/2016 08:14:21.330,1.11952
        ///01/04/2016 08:14:53.096,1.11940,1.11942,01/04/2016 08:14:21.330,1.11952,01/04/2016 08:14:53. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RENKOFEEDTESTS_4_BID {
            get {
                return ResourceManager.GetString("RENKOFEEDTESTS_4_BID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/05/2016 08:00:09.553,1.11757,1.11760,01/05/2016 08:00:00.092,1.11749,01/05/2016 08:00:09.553,1.11759
        ///01/05/2016 08:00:56.374,1.11767,1.11770,01/05/2016 08:00:09.553,1.11759,01/05/2016 08:00:56.374,1.11769
        ///01/05/2016 08:03:17.569,1.11745,1.11748,01/05/2016 08:00:56.374,1.11759,01/05/2016 08:03:17.569,1.11749
        ///01/05/2016 08:04:10.826,1.11737,1.11738,01/05/2016 08:03:17.569,1.11749,01/05/2016 08:04:10.826,1.11739
        ///01/05/2016 08:05:01.814,1.11726,1.11728,01/05/2016 08:04:10.826,1.11739,01/05/2016 08:05:01. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RENKOFEEDTESTS_5_ASK {
            get {
                return ResourceManager.GetString("RENKOFEEDTESTS_5_ASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/05/2016 08:00:09.451,1.11757,1.11758,01/05/2016 08:00:00.092,1.11746,01/05/2016 08:00:09.451,1.11756
        ///01/05/2016 08:00:56.221,1.11767,1.11768,01/05/2016 08:00:09.451,1.11756,01/05/2016 08:00:56.221,1.11766
        ///01/05/2016 08:02:47.097,1.11777,1.11778,01/05/2016 08:00:56.221,1.11766,01/05/2016 08:02:47.097,1.11776
        ///01/05/2016 08:03:13.682,1.11755,1.11758,01/05/2016 08:02:47.097,1.11766,01/05/2016 08:03:13.682,1.11756
        ///01/05/2016 08:03:17.365,1.11745,1.11749,01/05/2016 08:03:13.682,1.11756,01/05/2016 08:03:17. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RENKOFEEDTESTS_5_BID {
            get {
                return ResourceManager.GetString("RENKOFEEDTESTS_5_BID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/06/2016 08:00:05.040,1.11179,1.11182,01/06/2016 08:00:00.403,1.11167,01/06/2016 08:00:05.040,1.11177
        ///01/06/2016 08:00:30.819,1.11153,1.11156,01/06/2016 08:00:05.040,1.11167,01/06/2016 08:00:30.819,1.11157
        ///01/06/2016 08:01:01.607,1.11143,1.11146,01/06/2016 08:00:30.819,1.11157,01/06/2016 08:01:01.607,1.11147
        ///01/06/2016 08:01:47.402,1.11135,1.11136,01/06/2016 08:01:01.607,1.11147,01/06/2016 08:01:47.402,1.11137
        ///01/06/2016 08:02:11.900,1.11158,1.11160,01/06/2016 08:01:47.402,1.11147,01/06/2016 08:02:11. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RENKOFEEDTESTS_6_ASK {
            get {
                return ResourceManager.GetString("RENKOFEEDTESTS_6_ASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/06/2016 08:00:05.040,1.11179,1.11182,01/06/2016 08:00:00.403,1.11166,01/06/2016 08:00:05.040,1.11176
        ///01/06/2016 08:00:30.819,1.11153,1.11156,01/06/2016 08:00:05.040,1.11166,01/06/2016 08:00:30.819,1.11156
        ///01/06/2016 08:01:01.607,1.11143,1.11146,01/06/2016 08:00:30.819,1.11156,01/06/2016 08:01:01.607,1.11146
        ///01/06/2016 08:01:08.335,1.11135,1.11138,01/06/2016 08:01:01.607,1.11146,01/06/2016 08:01:08.335,1.11136
        ///01/06/2016 08:02:11.900,1.11158,1.11160,01/06/2016 08:01:08.335,1.11146,01/06/2016 08:02:11. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RENKOFEEDTESTS_6_BID {
            get {
                return ResourceManager.GetString("RENKOFEEDTESTS_6_BID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/07/2016 08:01:31.976,1.11124,1.11127,01/07/2016 08:00:00.327,1.11138,01/07/2016 08:01:31.976,1.11128
        ///01/07/2016 08:01:34.420,1.11115,1.11117,01/07/2016 08:01:31.976,1.11128,01/07/2016 08:01:34.420,1.11118
        ///01/07/2016 08:01:41.585,1.11105,1.11107,01/07/2016 08:01:34.420,1.11118,01/07/2016 08:01:41.585,1.11108
        ///01/07/2016 08:03:53.208,1.11094,1.11096,01/07/2016 08:01:41.585,1.11108,01/07/2016 08:03:53.208,1.11098
        ///01/07/2016 08:07:47.071,1.11086,1.11087,01/07/2016 08:03:53.208,1.11098,01/07/2016 08:07:47. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RENKOFEEDTESTS_7_ASK {
            get {
                return ResourceManager.GetString("RENKOFEEDTESTS_7_ASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/07/2016 08:01:31.976,1.11124,1.11127,01/07/2016 08:00:00.327,1.11135,01/07/2016 08:01:31.976,1.11125
        ///01/07/2016 08:01:36.043,1.11114,1.11117,01/07/2016 08:01:31.976,1.11125,01/07/2016 08:01:36.043,1.11115
        ///01/07/2016 08:01:44.025,1.11104,1.11106,01/07/2016 08:01:36.043,1.11115,01/07/2016 08:01:44.025,1.11105
        ///01/07/2016 08:03:53.208,1.11094,1.11096,01/07/2016 08:01:44.025,1.11105,01/07/2016 08:03:53.208,1.11095
        ///01/07/2016 08:07:47.275,1.11084,1.11086,01/07/2016 08:03:53.208,1.11095,01/07/2016 08:07:47. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RENKOFEEDTESTS_7_BID {
            get {
                return ResourceManager.GetString("RENKOFEEDTESTS_7_BID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/08/2016 08:00:15.585,1.10974,1.10975,01/08/2016 08:00:00.409,1.10986,01/08/2016 08:00:15.585,1.10976
        ///01/08/2016 08:03:36.493,1.10995,1.10998,01/08/2016 08:00:15.585,1.10986,01/08/2016 08:03:36.493,1.10996
        ///01/08/2016 08:04:52.686,1.10974,1.10975,01/08/2016 08:03:36.493,1.10986,01/08/2016 08:04:52.686,1.10976
        ///01/08/2016 08:08:51.106,1.10964,1.10965,01/08/2016 08:04:52.686,1.10976,01/08/2016 08:08:51.106,1.10966
        ///01/08/2016 08:09:29.470,1.10952,1.10953,01/08/2016 08:08:51.106,1.10966,01/08/2016 08:09:29. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RENKOFEEDTESTS_8_ASK {
            get {
                return ResourceManager.GetString("RENKOFEEDTESTS_8_ASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/08/2016 08:00:15.686,1.10972,1.10975,01/08/2016 08:00:00.409,1.10984,01/08/2016 08:00:15.686,1.10974
        ///01/08/2016 08:03:36.493,1.10995,1.10998,01/08/2016 08:00:15.686,1.10984,01/08/2016 08:03:36.493,1.10994
        ///01/08/2016 08:04:43.431,1.10973,1.10976,01/08/2016 08:03:36.493,1.10984,01/08/2016 08:04:43.431,1.10974
        ///01/08/2016 08:08:51.683,1.10963,1.10965,01/08/2016 08:04:43.431,1.10974,01/08/2016 08:08:51.683,1.10964
        ///01/08/2016 08:09:29.470,1.10952,1.10953,01/08/2016 08:08:51.683,1.10964,01/08/2016 08:09:29. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RENKOFEEDTESTS_8_BID {
            get {
                return ResourceManager.GetString("RENKOFEEDTESTS_8_BID", resourceCulture);
            }
        }
    }
}