//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquidEyes.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SquidEyes.UnitTests.Properties.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/04/2016 08:00:00.062,111982,01/04/2016 08:00:48.436,111992
        ///01/04/2016 08:00:48.436,111992,01/04/2016 08:01:01.089,111982
        ///01/04/2016 08:01:01.089,111982,01/04/2016 08:02:55.615,111992
        ///01/04/2016 08:02:55.615,111992,01/04/2016 08:04:14.785,112002
        ///01/04/2016 08:04:14.785,112002,01/04/2016 08:05:28.380,111992
        ///01/04/2016 08:05:28.380,111992,01/04/2016 08:06:45.013,111982
        ///01/04/2016 08:06:45.013,111982,01/04/2016 08:10:12.220,111972
        ///01/04/2016 08:10:12.220,111972,01/04/2016 08:11:41.394,111962
        ///01/04/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BRICKFEED_BASELINES_4 {
            get {
                return ResourceManager.GetString("BRICKFEED_BASELINES_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/05/2016 08:00:00.092,111747,01/05/2016 08:00:09.553,111757
        ///01/05/2016 08:00:09.553,111757,01/05/2016 08:00:56.272,111767
        ///01/05/2016 08:00:56.272,111767,01/05/2016 08:02:47.199,111777
        ///01/05/2016 08:02:47.199,111777,01/05/2016 08:02:52.171,111767
        ///01/05/2016 08:02:52.171,111767,01/05/2016 08:03:13.682,111757
        ///01/05/2016 08:03:13.682,111757,01/05/2016 08:03:17.569,111747
        ///01/05/2016 08:03:17.569,111747,01/05/2016 08:04:56.108,111737
        ///01/05/2016 08:04:56.108,111737,01/05/2016 08:05:01.920,111727
        ///01/05/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BRICKFEED_BASELINES_5 {
            get {
                return ResourceManager.GetString("BRICKFEED_BASELINES_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/06/2016 08:00:00.403,111166,01/06/2016 08:00:05.040,111176
        ///01/06/2016 08:00:05.040,111176,01/06/2016 08:00:26.421,111166
        ///01/06/2016 08:00:26.421,111166,01/06/2016 08:00:30.819,111156
        ///01/06/2016 08:00:30.819,111156,01/06/2016 08:01:01.607,111146
        ///01/06/2016 08:01:01.607,111146,01/06/2016 08:01:47.402,111136
        ///01/06/2016 08:01:47.402,111136,01/06/2016 08:02:08.036,111146
        ///01/06/2016 08:02:08.036,111146,01/06/2016 08:02:11.900,111156
        ///01/06/2016 08:02:11.900,111156,01/06/2016 08:02:17.728,111166
        ///01/06/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BRICKFEED_BASELINES_6 {
            get {
                return ResourceManager.GetString("BRICKFEED_BASELINES_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/07/2016 08:00:00.327,111136,01/07/2016 08:01:31.976,111126
        ///01/07/2016 08:01:31.976,111126,01/07/2016 08:01:35.840,111116
        ///01/07/2016 08:01:35.840,111116,01/07/2016 08:01:44.025,111106
        ///01/07/2016 08:01:44.025,111106,01/07/2016 08:02:01.959,111116
        ///01/07/2016 08:02:01.959,111116,01/07/2016 08:02:23.795,111106
        ///01/07/2016 08:02:23.795,111106,01/07/2016 08:03:53.208,111096
        ///01/07/2016 08:03:53.208,111096,01/07/2016 08:05:51.674,111106
        ///01/07/2016 08:05:51.674,111106,01/07/2016 08:06:58.870,111096
        ///01/07/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BRICKFEED_BASELINES_7 {
            get {
                return ResourceManager.GetString("BRICKFEED_BASELINES_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/08/2016 08:00:00.409,110985,01/08/2016 08:00:15.585,110975
        ///01/08/2016 08:00:15.585,110975,01/08/2016 08:00:35.370,110985
        ///01/08/2016 08:00:35.370,110985,01/08/2016 08:03:36.493,110995
        ///01/08/2016 08:03:36.493,110995,01/08/2016 08:04:13.230,110985
        ///01/08/2016 08:04:13.230,110985,01/08/2016 08:04:43.431,110975
        ///01/08/2016 08:04:43.431,110975,01/08/2016 08:05:05.985,110985
        ///01/08/2016 08:05:05.985,110985,01/08/2016 08:06:57.644,110975
        ///01/08/2016 08:06:57.644,110975,01/08/2016 08:08:51.106,110965
        ///01/08/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BRICKFEED_BASELINES_8 {
            get {
                return ResourceManager.GetString("BRICKFEED_BASELINES_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/04/2016 08:00:00.062,1.11982,1.11983
        ///01/04/2016 08:00:00.164,1.11984,1.11985
        ///01/04/2016 08:00:00.576,1.11986,1.11988
        ///01/04/2016 08:00:00.678,1.11987,1.11988
        ///01/04/2016 08:00:00.779,1.11987,1.11989
        ///01/04/2016 08:00:01.083,1.11987,1.11988
        ///01/04/2016 08:00:01.337,1.11987,1.11989
        ///01/04/2016 08:00:06.658,1.11987,1.11990
        ///01/04/2016 08:00:06.760,1.11990,1.11992
        ///01/04/2016 08:00:06.861,1.11991,1.11993
        ///01/04/2016 08:00:06.963,1.11991,1.11994
        ///01/04/2016 08:00:07.702,1.11990,1.11994
        ///01/04/2016 08:00:08. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20160104_NYC_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20160104_NYC_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160104_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160104_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/05/2016 08:00:00.092,1.11746,1.11749
        ///01/05/2016 08:00:00.345,1.11746,1.11748
        ///01/05/2016 08:00:00.446,1.11746,1.11749
        ///01/05/2016 08:00:00.791,1.11747,1.11749
        ///01/05/2016 08:00:00.893,1.11747,1.11750
        ///01/05/2016 08:00:01.789,1.11746,1.11748
        ///01/05/2016 08:00:01.890,1.11746,1.11749
        ///01/05/2016 08:00:02.042,1.11747,1.11749
        ///01/05/2016 08:00:02.194,1.11746,1.11749
        ///01/05/2016 08:00:02.397,1.11747,1.11750
        ///01/05/2016 08:00:02.498,1.11746,1.11750
        ///01/05/2016 08:00:03.060,1.11748,1.11750
        ///01/05/2016 08:00:06. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20160105_NYC_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20160105_NYC_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160105_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160105_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/06/2016 08:00:00.403,1.11166,1.11167
        ///01/06/2016 08:00:00.505,1.11165,1.11167
        ///01/06/2016 08:00:00.606,1.11165,1.11168
        ///01/06/2016 08:00:00.707,1.11165,1.11167
        ///01/06/2016 08:00:00.852,1.11164,1.11167
        ///01/06/2016 08:00:00.954,1.11165,1.11167
        ///01/06/2016 08:00:01.119,1.11165,1.11168
        ///01/06/2016 08:00:01.220,1.11166,1.11169
        ///01/06/2016 08:00:01.322,1.11168,1.11170
        ///01/06/2016 08:00:01.423,1.11172,1.11173
        ///01/06/2016 08:00:01.525,1.11172,1.11174
        ///01/06/2016 08:00:01.676,1.11173,1.11175
        ///01/06/2016 08:00:01. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20160106_NYC_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20160106_NYC_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160106_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160106_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/07/2016 08:00:00.327,1.11135,1.11138
        ///01/07/2016 08:00:00.985,1.11135,1.11136
        ///01/07/2016 08:00:01.087,1.11134,1.11137
        ///01/07/2016 08:00:01.189,1.11134,1.11135
        ///01/07/2016 08:00:01.290,1.11132,1.11133
        ///01/07/2016 08:00:01.393,1.11130,1.11134
        ///01/07/2016 08:00:01.494,1.11130,1.11133
        ///01/07/2016 08:00:02.047,1.11130,1.11134
        ///01/07/2016 08:00:02.148,1.11131,1.11134
        ///01/07/2016 08:00:02.300,1.11132,1.11135
        ///01/07/2016 08:00:02.753,1.11134,1.11135
        ///01/07/2016 08:00:02.805,1.11135,1.11136
        ///01/07/2016 08:00:02. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20160107_NYC_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20160107_NYC_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160107_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160107_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/08/2016 08:00:00.409,1.10984,1.10986
        ///01/08/2016 08:00:00.460,1.10982,1.10986
        ///01/08/2016 08:00:00.613,1.10983,1.10986
        ///01/08/2016 08:00:01.036,1.10982,1.10986
        ///01/08/2016 08:00:01.240,1.10983,1.10986
        ///01/08/2016 08:00:01.393,1.10982,1.10986
        ///01/08/2016 08:00:02.525,1.10983,1.10986
        ///01/08/2016 08:00:04.664,1.10982,1.10985
        ///01/08/2016 08:00:07.554,1.10982,1.10984
        ///01/08/2016 08:00:08.169,1.10982,1.10985
        ///01/08/2016 08:00:08.270,1.10981,1.10984
        ///01/08/2016 08:00:08.371,1.10982,1.10984
        ///01/08/2016 08:00:09. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DC_EURUSD_20160108_NYC_EST_CSV {
            get {
                return ResourceManager.GetString("DC_EURUSD_20160108_NYC_EST_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160108_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160108_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
