//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SquidEyes.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SquidEyes.UnitTests.Properties.TestData", typeof(TestData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/04/2016 08:00:00.062,111982,01/04/2016 08:00:48.436,111992
        ///01/04/2016 08:00:48.436,111992,01/04/2016 08:01:01.089,111982
        ///01/04/2016 08:01:01.089,111982,01/04/2016 08:02:55.615,111992
        ///01/04/2016 08:02:55.615,111992,01/04/2016 08:04:14.785,112002
        ///01/04/2016 08:04:14.785,112002,01/04/2016 08:05:28.380,111992
        ///01/04/2016 08:05:28.380,111992,01/04/2016 08:06:45.013,111982
        ///01/04/2016 08:06:45.013,111982,01/04/2016 08:10:12.220,111972
        ///01/04/2016 08:10:12.220,111972,01/04/2016 08:11:41.394,111962
        ///01/04/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BRICKFEED_BASELINES_4 {
            get {
                return ResourceManager.GetString("BRICKFEED_BASELINES_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/05/2016 08:00:00.092,111747,01/05/2016 08:00:09.553,111757
        ///01/05/2016 08:00:09.553,111757,01/05/2016 08:00:56.272,111767
        ///01/05/2016 08:00:56.272,111767,01/05/2016 08:02:47.199,111777
        ///01/05/2016 08:02:47.199,111777,01/05/2016 08:02:52.171,111767
        ///01/05/2016 08:02:52.171,111767,01/05/2016 08:03:13.682,111757
        ///01/05/2016 08:03:13.682,111757,01/05/2016 08:03:17.569,111747
        ///01/05/2016 08:03:17.569,111747,01/05/2016 08:04:56.108,111737
        ///01/05/2016 08:04:56.108,111737,01/05/2016 08:05:01.920,111727
        ///01/05/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BRICKFEED_BASELINES_5 {
            get {
                return ResourceManager.GetString("BRICKFEED_BASELINES_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/06/2016 08:00:00.403,111166,01/06/2016 08:00:05.040,111176
        ///01/06/2016 08:00:05.040,111176,01/06/2016 08:00:26.421,111166
        ///01/06/2016 08:00:26.421,111166,01/06/2016 08:00:30.819,111156
        ///01/06/2016 08:00:30.819,111156,01/06/2016 08:01:01.607,111146
        ///01/06/2016 08:01:01.607,111146,01/06/2016 08:01:47.402,111136
        ///01/06/2016 08:01:47.402,111136,01/06/2016 08:02:08.036,111146
        ///01/06/2016 08:02:08.036,111146,01/06/2016 08:02:11.900,111156
        ///01/06/2016 08:02:11.900,111156,01/06/2016 08:02:17.728,111166
        ///01/06/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BRICKFEED_BASELINES_6 {
            get {
                return ResourceManager.GetString("BRICKFEED_BASELINES_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/07/2016 08:00:00.327,111136,01/07/2016 08:01:31.976,111126
        ///01/07/2016 08:01:31.976,111126,01/07/2016 08:01:35.840,111116
        ///01/07/2016 08:01:35.840,111116,01/07/2016 08:01:44.025,111106
        ///01/07/2016 08:01:44.025,111106,01/07/2016 08:02:01.959,111116
        ///01/07/2016 08:02:01.959,111116,01/07/2016 08:02:23.795,111106
        ///01/07/2016 08:02:23.795,111106,01/07/2016 08:03:53.208,111096
        ///01/07/2016 08:03:53.208,111096,01/07/2016 08:05:51.674,111106
        ///01/07/2016 08:05:51.674,111106,01/07/2016 08:06:58.870,111096
        ///01/07/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BRICKFEED_BASELINES_7 {
            get {
                return ResourceManager.GetString("BRICKFEED_BASELINES_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 01/08/2016 08:00:00.409,110985,01/08/2016 08:00:15.585,110975
        ///01/08/2016 08:00:15.585,110975,01/08/2016 08:00:35.370,110985
        ///01/08/2016 08:00:35.370,110985,01/08/2016 08:03:36.493,110995
        ///01/08/2016 08:03:36.493,110995,01/08/2016 08:04:13.230,110985
        ///01/08/2016 08:04:13.230,110985,01/08/2016 08:04:43.431,110975
        ///01/08/2016 08:04:43.431,110975,01/08/2016 08:05:05.985,110985
        ///01/08/2016 08:05:05.985,110985,01/08/2016 08:06:57.644,110975
        ///01/08/2016 08:06:57.644,110975,01/08/2016 08:08:51.106,110965
        ///01/08/20 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BRICKFEED_BASELINES_8 {
            get {
                return ResourceManager.GetString("BRICKFEED_BASELINES_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160104_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160104_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160105_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160105_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160106_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160106_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160107_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160107_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] DC_EURUSD_20160108_NYC_EST_STS {
            get {
                object obj = ResourceManager.GetObject("DC_EURUSD_20160108_NYC_EST_STS", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
